### ISSUE TITLE
CW3

### ISSUE THREAD

**Issue by kovach-dmitry** [oleksandrblazhko/ai202-kovach#15]
**Завдання №1:**
Один екземпляр класу "Користувач" може отримати декілька екземплярів класу "Поетична література".

**Завдання №2:**
Перевагою вибору реляційної моделі даних були такі пункти, як:
1. Швидке виконання шляхом надбудови;
2. Більш чітке введення і редагування даних;
4. Одночасне редагування однотипних даних;
5. Висока цілісність даних. Зміни в прикладній програмі при зміні реляційної БД мінімальні;
6. Особистий досвід створення реляційних схем даних.

Недоліки вибору реляційної моделі в порівнянні із Json-моделлю:
1. Складність поєктування реляційної моделі в порівнянні із Json-моделлю;
2. Json-модель швидше читати і писати.

**Comment by oleksandrblazhko** [comment]
2
