### ISSUE TITLE
CW4

### ISSUE THREAD

**Issue by kovach-dmitry** [oleksandrblazhko/ai202-kovach#22]
Завдання №1:
[Посилання на файл із скриптом](https://github.com/oleksandrblazhko/ai202-kovach/blob/main/2-SoftwareDesign/2.4-DetailedDataSchema/RelationDB_DetailedDataSchema.sql)
ALTER TABLE Poetic_literature ADD CONSTRAINT author_template
    CHECK (regexp_like(author, '^name:\s\w{1,16},surname:\s\w{0,22},last_name:\s\w{1,26}[^*&$@]$'));

Завдання №2:
[Посилання на діаграму програмних класів](https://github.com/oleksandrblazhko/ai202-kovach/blob/main/2-SoftwareDesign/2.5-UMLProgramClasses/UML-diagram_of_program_classes.jpg)

- Зв`язок  між класом "List of Poetic Literature" та класом "Poetic Literature" було перетворено на список із спеціальним типом даних "Poetic Literature".

- Зв`язок  між класом "Portry search API" та класом "Poetic Literature" було перетворено на функцію "findPoetLit()", що надає об'єкти класу "Poetic Literature".

- Зв`язок  між класом "Self respect development complex search API" та класом "Self respect development complex" було перетворено на функцію "findSelfResComplex()", що надає об'єкти класу "Self respect development complex".

**Comment by oleksandrblazhko** [comment]
3 бали
