### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai202-kovach#6]
https://drive.google.com/file/d/1Jupr5VQFJpOmHJSJY9Vu2JgmrSXgxk2I/view

**Comment by kovach-dmitry** [comment]
**Завдання №1:**
Самопоовага є доступною, через те, що вона є не потребує фінансових або виробничих потреб до продукту, вона зедежить від психічних ресурсів самого користувача.
Самоповага є зрозумілою для будь-якої з мов користувача.
Самоповага це необхідність для психологічно здорового життя людини.
Самоповага буде потрібна будь якій людини, ще довгий час, через особливості людської психіки.

**Завдання №2:**
Метою програмного продукту є допомога у задоволенні потреби споживача у фінансовій стабільності, для можливості займатися літературною поезією в умовах чистого довколишнього повітря та підтримки відчуття самоповаги.
Прецидент Розрахувати фінанси - допоможе споживачу у плануванні власних фінансів, що певним чином покращить його фінансовий стан.
Прецидент Знайти поетичну літературу - задовільнить потребу у літературній поезії, допомагаючи знаходити цікавлючу користувача поезію.
Прецидент Проробити комплекс розвитку самоповаги - допоможе користувачу розвинути свою самоповагу, за допомогою різних пропонуємих психологічних програм.

**Comment by oleksandrblazhko** [comment]
завдання 1 - 0.5, бо треба було аналізувати інформаційні потреби, а не реальні.
завдання 2 - 1.5 бали.
оцінка = 2 бали
